name: domen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:
  gap: ^3.0.1
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Nova Square
      fonts:
        - asset: assets/fonts/nova_square/NovaSquare-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
        - asset: assets/fonts/merriweather/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/merriweather/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/merriweather/Merriweather-Italic.ttf
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
        - asset: assets/fonts/merriweather/Merriweather-LightItalic.ttf
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf


flutter_gen:
  output: lib/generated_assets/
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
